### PR TITLE
Fix for "azurerm_role_assignment" "disks_resource_group_role_assignment" when multiple clusters

### PR DESCRIPTION
**Pull request by thomast1906**
### Change description ###
Fix for "azurerm_role_assignment" "disks_resource_group_role_assignment" when multiple clusters
- sbox etc, we deploy 00/01
- Deploys fine when we select deploy_all
- If I delete sbox01, then redeploy sbox01
- I got an error to say the role_assignment exists
https://dev.azure.com/hmcts/CNP/_build/results?buildId=156667&view=logs&j=9529ead6-39ae-5319-1740-9d2035106bd6&t=82916ec7-6bfc-5be6-8e43-ad333d8f6c48&l=32 

This just creates "azurerm_role_assignment" "disks_resource_group_role_assignment" with cluster00 only. 
https://dev.azure.com/hmcts/CNP/_build/results?buildId=156679&view=logs&j=9529ead6-39ae-5319-1740-9d2035106bd6&t=89b2e481-5d95-5be1-d64b-e101e3d88784&l=475 

I believe this was initially implemented for Jenkins/PVC

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
as a hack it's ok, but not ideal =/

**Comment by thomast1906** [comment]
@timja Should we move it to a var to be enabled only for Jenkins clusters?

**Comment by timja** [comment]
> @timja Should we move it to a var to be enabled only for Jenkins clusters?

yes i think that would be better.

have you tracked down what is causing this? can you reproduce locally?

**Review by endakelly — APPROVED** [review]

**Comment by thomast1906** [comment]
> > @timja Should we move it to a var to be enabled only for Jenkins clusters?
> 
> yes i think that would be better.
> 
> have you tracked down what is causing this? can you reproduce locally?

Yup - reproduced locally to fix initially. 

From what I can see, when both azurerm_role_assignment get added initially it must not have an adequate timeout/check to confirm the error as below 
`Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."`

When redeploying either cluster, this error appears. 

Will look at flagging just for Jenkins only clusters.

**Comment by thomast1906** [comment]
@timja @endakelly have updated with flag approach.

PRs for relevant repos
https://github.com/hmcts/aks-sds-deploy/pull/82
https://github.com/hmcts/aks-cft-deploy/pull/65

**Pull request merged**
