### PR TITLE
DTSPO-4794 Add Azure AZ

### PR DESCRIPTION
**Pull request by mokainos**

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
this needs to be added conditionally to not break other clusters

see

https://github.com/hmcts/aks-module-kubernetes/blob/dtspo-4794_new/12-kubernetes-cluster.tf#L38-L39

you can probably set it to `null` if it's not in use

**Comment by timja** [comment]
Have you tested this without setting it?

**Review by timja — CHANGES_REQUESTED** [review]
please confirm you've tested without availability zones set

**Comment by mokainos** [comment]
> please confirm you've tested without availability zones set

https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=175482&view=l[…]-5319-1740-9d2035106bd6&t=82916ec7-6bfc-5be6-8e43-ad333d8f6c48  

Run the pipeline in demo env by reverting the changes

**Review by timja — APPROVED** [review]

**Pull request merged**
